Repository AutoPas/AutoPas, pull requests merged in 2019-01, with the labels that each got.

#148 container cleanup
  examples/cluster-test/CMakeLists.txt
  examples/sph-traversals/CMakeLists.txt
  examples/sph-traversals/sph-traversals.cpp
  src/autopas/autopasIncludes.h
  src/autopas/containers/ParticleContainer.h
  src/autopas/containers/cellPairTraversals/C01BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C01Traversal.h
  src/autopas/containers/cellPairTraversals/C08BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C08Traversal.h
  src/autopas/containers/cellPairTraversals/C18BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C18Traversal.h
  src/autopas/containers/cellPairTraversals/CellPairTraversal.h
  src/autopas/containers/cellPairTraversals/CellPairTraversalInterface.h
  src/autopas/containers/cellPairTraversals/DummyTraversal.h
  src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
  src/autopas/containers/cellPairTraversals/TraversalInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/directSum/DirectSumTraversal.h
  src/autopas/containers/directSum/DirectSumTraversalInterface.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C08CellHandler.h
  src/autopas/containers/linkedCells/traversals/C08Traversal.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/containers/linkedCells/traversals/LinkedCellTraversalInterface.h
  src/autopas/containers/linkedCells/traversals/SlicedTraversal.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCellsHelpers.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C01TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C18TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/SlicedTraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VerletListsCellsTraversal.h
  src/autopas/pairwiseFunctors/Functor.h
  src/autopas/selectors/ContainerSelector.h
  src/autopas/selectors/TraversalSelector.h
  tests/testAutopas/ArcherShouldReportThis.cpp
  tests/testAutopas/C01TraversalTest.cpp
  tests/testAutopas/C01TraversalTest.h
  tests/testAutopas/C08TraversalTest.cpp
  tests/testAutopas/C18TraversalTest.cpp
  tests/testAutopas/C18TraversalTest.h
  tests/testAutopas/DirectSumContainerTest.h
  tests/testAutopas/DirectSumTraversalTest.cpp
  tests/testAutopas/LinkedCellsTest.h
  tests/testAutopas/LinkedCellsVersusVerletListsCellsTest.cpp
  tests/testAutopas/SlicedTraversalTest.cpp
  tests/testAutopas/SlicedTraversalTest.h
  tests/testAutopas/TraversalRaceConditionTest.h
  tests/testAutopas/VerletListsCellsTest.cpp
  tests/testAutopas/VerletListsCellsTraversalTest.cpp
  tests/testAutopas/mocks/MockFunctor.h
  tests/testAutopas/mocks/MockVerletLists.h
Labels: refactoring

#151 Make autopas use a proper lock class
  src/autopas/cells/FullParticleCell.h
  src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
  src/autopas/utils/WrapOpenMP.h
Labels: openmp

#158 Enable and test rebuilding of AutoPas
  src/autopas/AutoPas.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  tests/testAutopas/tests/autopasInterface/AutoPasTest.cpp
Labels: ls1-integration

#157 More utils
  README.md
  examples/md-flexible/MDFlexParser.cpp
  src/autopas/containers/cellPairTraversals/TraversalInterface.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/utils/StringUtils.h
  tests/testAutopas/tests/utils/StringUtilsTest.cpp
  tests/testAutopas/tests/utils/StringUtilsTest.h
Labels: enhancement, ls1-integration

#159 Fixes CellBlock3D wrongly assigning cell to some particles
  src/autopas/containers/CellBlock3D.h
  tests/testAutopas/tests/containers/CellBlock3DTest.cpp
  tests/testAutopas/tests/containers/CellBlock3DTest.h
Labels: bug, particle duplication or loss

#160 Global value calculation for verlet lists SoA functor
  src/autopas/pairwiseFunctors/LJFunctor.h
  tests/testAutopas/tests/pairwiseFunctors/LJFunctorTest.cpp
  tests/testAutopas/tests/pairwiseFunctors/LJFunctorTest.h
Labels: ls1-integration, optimization

#154 LJ Functor with AVX Intrinsics
  examples/md-flexible/MDFlexParser.cpp
  examples/md-flexible/MDFlexParser.h
  examples/md-flexible/main.cpp
  src/autopas/pairwiseFunctors/LJFunctor.h
  src/autopas/pairwiseFunctors/LJFunctorAVX.h
  tests/testAutopas/tests/pairwiseFunctors/LJFunctorAVXTest.cpp
  tests/testAutopas/tests/pairwiseFunctors/LJFunctorAVXTest.h
Labels: optimization

#165 verlet list AutoPas interface usability changes
  src/autopas/AutoPas.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  tests/testAutopas/tests/autopasInterface/AutoPasTest.cpp
Labels: ls1-integration
