Repository AutoPas/AutoPas, pull requests merged in 2019-09, with the labels that each got.

#336 Documentation Linked-Cells
  .gitignore
  docs/Doxyfile.in
  docs/graphics/C01.png
  docs/graphics/C01.tex
  docs/graphics/C01_combined.png
  docs/graphics/C01_combined.tex
  docs/graphics/C01_combined_cache.png
  docs/graphics/C01_combined_cache.tex
  docs/graphics/C01_combined_legend.png
  docs/graphics/C01_combined_legend.tex
  docs/graphics/C08.png
  docs/graphics/C08.tex
  docs/graphics/C08_domain.png
  docs/graphics/C08_domain.tex
  docs/graphics/C18.png
  docs/graphics/C18.tex
  docs/graphics/C18_domain.png
  docs/graphics/C18_domain.tex
  docs/graphics/SortingPrinciple.png
  docs/graphics/SortingPrinciple.tex
  src/autopas/cells/SortedCellView.h
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C08Traversal.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
Labels: documentation

#330 Bugfix collection and default value removal
  examples/CMakeLists.txt
  examples/benchmark-cuda/main.cpp
  examples/sph-traversals/CMakeLists.txt
  examples/sph-traversals/sph-traversals.cpp
  src/autopas/containers/cellPairTraversals/C01BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C04BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C08BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C18BasedTraversal.h
  src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/directSum/DirectSumTraversal.h
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h
  src/autopas/containers/linkedCells/traversals/C04SoATraversal.h
  src/autopas/containers/linkedCells/traversals/C04Traversal.h
  src/autopas/containers/linkedCells/traversals/C08CellHandler.h
  src/autopas/containers/linkedCells/traversals/C08Traversal.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/containers/linkedCells/traversals/SlicedTraversal.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletLists/neighborLists/asBuild/C08TraversalColorChangeNotify.h
  src/autopas/containers/verletListsCellBased/verletLists/neighborLists/asBuild/VerletNeighborListAsBuild.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCellsHelpers.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C01TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C18TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/SlicedTraversalVerlet.h
  src/autopas/pairwiseFunctors/CellFunctor.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/selectors/TraversalSelectorInfo.h
  src/autopas/utils/StaticSelectorMacros.h
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/containers/CudaTraversalVersusDirectSumTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusDirectSumTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVarVerletListsTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletClusterListsTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsCellsTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsTest.cpp
  tests/testAutopas/tests/containers/directSum/DirectSumTraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/C01TraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/C04SoATraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/SlicedTraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTest.cpp
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.cpp
  tests/testAutopas/tests/selectors/TraversalSelectorTest.cpp
  tests/testAutopas/tests/sph/SPHTest.cpp
Labels: bug, ls1-integration, refactoring

#350 Adds const iterators to AutoPas
  README.md
  src/autopas/AutoPas.h
  src/autopas/LogicHandler.h
  src/autopas/autopasIncludes.h
  src/autopas/cells/FullParticleCell.h
  src/autopas/cells/ParticleCell.h
  src/autopas/cells/RMMParticleCell3T.h
  src/autopas/cells/SortedCellView.h
  src/autopas/containers/CellBlock3D.h
  src/autopas/containers/ParticleContainer.h
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/iterators/ParticleIterator.h
  src/autopas/iterators/ParticleIteratorInterface.h
  src/autopas/iterators/ParticleIteratorWrapper.h
  src/autopas/iterators/RegionParticleIterator.h
  src/autopas/iterators/SingleCellIterator.h
  src/autopas/iterators/SingleCellIteratorInterface.h
  src/autopas/iterators/SingleCellIteratorWrapper.h
  src/autopas/particles/MoleculeLJ.cpp
  src/autopas/particles/MoleculeLJ.h
  src/autopas/particles/ParticleBase.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/ContainerSelector.h
  src/autopas/sph/SPHParticle.h
  src/autopas/utils/SoA.h
  tests/testAutopas/tests/autopasInterface/AutoPasTest.cpp
  tests/testAutopas/tests/iterators/ParticleIteratorTest.cpp
Labels: enhancement

#351 Provide type aliases for the iterator types
  src/autopas/AutoPas.h
  src/autopas/iterators/ParticleIteratorWrapper.h
Labels: ls1-integration

#357 fix all tuning-strategies using the last measured time
  src/autopas/selectors/AutoTuner.h
Labels: auto-tuning, bug
