Repository AutoPas/AutoPas, pull requests merged in 2019-05, with the labels that each got.

#186 Allow cell sizes > 1.0 for linked cells, argument validation, refactoring
  examples/md-flexible/CMakeLists.txt
  examples/md-flexible/MDFlexParser.cpp
  examples/md-flexible/MDFlexParser.h
  examples/md-flexible/main.cpp
  examples/md-flexible/measurePerf.sh
  src/autopas/AutoPas.h
  src/autopas/containers/CellBlock3D.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/ContainerSelector.h
  tests/testAutopas/testingHelpers/GaussianGenerator.h
  tests/testAutopas/testingHelpers/GridGenerator.h
  tests/testAutopas/testingHelpers/RandomGenerator.cpp
  tests/testAutopas/testingHelpers/RandomGenerator.h
  tests/testAutopas/tests/autopasInterface/AutoPasTest.cpp
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.h
  tests/testAutopas/tests/containers/CellBlock3DTest.cpp
  tests/testAutopas/tests/containers/CellBlock3DTest.h
  tests/testAutopas/tests/selectors/AutoTunerTest.cpp
  tests/testAutopas/tests/selectors/ContainerSelectorTest.cpp
  tests/testAutopas/tests/utils/TimerTest.cpp
Labels: enhancement

#197 Verlet list fixes (disabled newton3, changing newton3)
  docs/Doxyfile.in
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/pairwiseFunctors/FlopCounterFunctor.h
  src/autopas/utils/Logger.h
  src/autopas/utils/StaticSelectorMacros.h
  src/autopas/utils/StaticSelectors.h
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsTest.h
  tests/testAutopas/tests/containers/verletLists/VerletListsTest.cpp
Labels: bug, ls1-integration

#205 Refactor LinkedCellsVersusDirectSum Test
  tests/testAutopas/tests/containers/LinkedCellsVersusDirectSumTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusDirectSumTest.h
Labels: refactoring

#201 Allow cell sizes < 1.0 for linked cells, refactoring
  docs/C08TraversalScheme.py
  src/autopas/containers/CellBlock3D.h
  src/autopas/containers/cellPairTraversals/C01BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C08BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C18BasedTraversal.h
  src/autopas/containers/cellPairTraversals/CBasedTraversal.h
  src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C08CellHandler.h
  src/autopas/containers/linkedCells/traversals/C08Traversal.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/containers/linkedCells/traversals/SlicedTraversal.h
  src/autopas/iterators/SingleCellIteratorInterface.h
  src/autopas/pairwiseFunctors/CellFunctor.h
  src/autopas/selectors/OptimumSelector.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/utils/ArrayMath.h
  src/autopas/utils/ExceptionHandler.h
  tests/testAutopas/testingHelpers/NumThreadGuard.h
  tests/testAutopas/tests/containers/CellBlock3DTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/C01TraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/C01TraversalTest.h
  tests/testAutopas/tests/containers/linkedCells/traversals/C08TraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/C08TraversalTest.h
  tests/testAutopas/tests/containers/linkedCells/traversals/C18TraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/C18TraversalTest.h
  tests/testAutopas/tests/containers/linkedCells/traversals/SlicedTraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.h
  tests/testAutopas/tests/pairwiseFunctors/FlopCounterTest.cpp
  tests/testAutopas/tests/utils/ArrayMathTest.cpp
Labels: enhancement

#217 adapt updateContainer interface change
  src/autopas/AutoPas.h
  src/autopas/autopasIncludes.h
  src/autopas/cells/FullParticleCell.h
  src/autopas/cells/RMMParticleCell2T.h
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/particles/Particle.h
  src/autopas/utils/AutoPasMacros.h
  tests/testAutopas/mocks/MockVerletLists.h
  tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
  tests/testAutopas/tests/containers/directSum/DirectSumContainerTest.cpp
  tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
  tests/testAutopas/tests/containers/verletLists/VerletListsTest.cpp
Labels: ls1-integration

#220 Adapt owed particle bahavior [ad PR #215]
  src/autopas/containers/CellBlock3D.h
  src/autopas/containers/CellBorderAndFlagManager.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/iterators/ParticleIterator.h
  src/autopas/iterators/RegionParticleIterator.h
  src/autopas/particles/Particle.h
  tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
  tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.h
  tests/testAutopas/tests/containers/directSum/DirectSumContainerTest.cpp
  tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
  tests/testAutopas/tests/selectors/ContainerSelectorTest.cpp
Labels: enhancement, ls1-integration, tests

#227 Refactored TraversalSelector to remove a lot of unnecessary dependencies
  examples/sphDiagramGeneration/sph-diagram-generation.cpp
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/selectors/TraversalSelectorInfo.h
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/selectors/TraversalSelectorTest.cpp
Labels: refactoring
