Repository AutoPas/AutoPas, pull requests merged in 2019-07, with the labels that each got.

#294 how to use the docker containers
  .github/CONTRIBUTING.md
Labels: documentation

#274 Particle refactoring
  src/autopas/pairwiseFunctors/LJFunctor.h
  src/autopas/pairwiseFunctors/LJFunctorAVX.h
  src/autopas/particles/Particle.h
  src/autopas/particles/ParticleBase.h
Labels: refactoring

#255 Import ls1-mardyn c04 traversal
  src/autopas/containers/CompatibleTraversals.h
  src/autopas/containers/linkedCells/traversals/C04Traversal.h
  src/autopas/containers/linkedCells/traversals/C08CellHandler.h
  src/autopas/options/TraversalOption.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/utils/StringUtils.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/selectors/AutoTunerTest.cpp
  tests/testAutopas/tests/utils/StringUtilsTest.cpp
Labels: enhancement

#290 Cutoff sanity check
  src/autopas/AutoPas.h
  src/autopas/cells/SortedCellView.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCellsHelpers.h
  src/autopas/pairwiseFunctors/FlopCounterFunctor.h
  src/autopas/pairwiseFunctors/Functor.h
  src/autopas/pairwiseFunctors/LJFunctor.h
  src/autopas/pairwiseFunctors/LJFunctorAVX.h
  src/autopas/sph/SPHCalcDensityFunctor.h
  src/autopas/sph/SPHCalcHydroForceFunctor.h
  tests/testAutopas/mocks/MockFunctor.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.h
Labels: bug

#296 remove cxx extensions
  CMakeLists.txt
Labels: cmake

#262 Traversal for VerletClusterLists + Refactoring
  examples/cluster-test/cluster-test.cpp
  examples/md-flexible/measurePerf.sh
  examples/sph-traversals/CMakeLists.txt
  examples/sph-traversals/sph-traversals.cpp
  src/autopas/autopasIncludes.h
  src/autopas/containers/CompatibleTraversals.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletClusterLists/VerletClusterMaths.h
  src/autopas/containers/verletClusterLists/traversals/VerletClustersTraversal.h
  src/autopas/containers/verletClusterLists/traversals/VerletClustersTraversalInterface.h
  src/autopas/options/TraversalOption.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/utils/StringUtils.h
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletClusterListsTest.cpp
  tests/testAutopas/tests/containers/verletClusterLists/VerletClusterListsTest.cpp
  tests/testAutopas/tests/selectors/AutoTunerTest.cpp
  tests/testAutopas/tests/utils/StringUtilsTest.cpp
Labels: refactoring

#293 Functor refactoring
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
  src/autopas/pairwiseFunctors/FlopCounterFunctor.h
  src/autopas/pairwiseFunctors/Functor.h
  src/autopas/pairwiseFunctors/LJFunctor.h
  src/autopas/pairwiseFunctors/LJFunctorAVX.h
  src/autopas/particles/ParticleBase.h
  src/autopas/sph/SPHCalcDensityFunctor.h
  src/autopas/sph/SPHCalcHydroForceFunctor.h
  src/autopas/sph/SPHParticle.h
  src/autopas/utils/SoA.h
  tests/testAutopas/mocks/MockFunctor.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.h
Labels: refactoring

#260 Removed all templates from iteratePairwise() and made it virtual
  examples/benchmark-cuda/main.cpp
  examples/cluster-test/cluster-test.cpp
  examples/sph-traversals/sph-traversals.cpp
  examples/sph/sph-main.cpp
  examples/sphDiagramGeneration/sph-diagram-generation.cpp
  src/autopas/autopasIncludes.h
  src/autopas/containers/ParticleContainer.h
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/TraversalInterface.h
  src/autopas/containers/cellPairTraversals/CBasedTraversal.h
  src/autopas/containers/cellPairTraversals/CellPairTraversal.h
  src/autopas/containers/cellPairTraversals/DummyTraversal.h
  src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/directSum/DirectSumTraversal.h
  src/autopas/containers/directSum/DirectSumTraversalInterface.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/linkedCells/traversals/C01CudaTraversal.h
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C04Traversal.h
  src/autopas/containers/linkedCells/traversals/C08Traversal.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/containers/linkedCells/traversals/LinkedCellTraversalInterface.h
  src/autopas/containers/linkedCells/traversals/SlicedTraversal.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletClusterLists/traversals/VerletClustersTraversal.h
  src/autopas/containers/verletClusterLists/traversals/VerletClustersTraversalInterface.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletLists/traversals/TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletLists/traversals/VerletTraversalInterface.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C01TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C18TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/SlicedTraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VerletListsCellsTraversal.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/utils/StaticSelectors.h
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/containers/CudaTraversalVersusDirectSumTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusDirectSumTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletClusterListsTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsCellsTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsCellsTest.h
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsTest.cpp
  tests/testAutopas/tests/containers/directSum/DirectSumTraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/SlicedTraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/containers/verletClusterLists/VerletClusterListsTest.cpp
  tests/testAutopas/tests/containers/verletLists/VerletListsTest.cpp
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTest.cpp
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.cpp
  tests/testAutopas/tests/sph/SPHTest.cpp
Labels: refactoring

#265 Autotune bayesian
  cmake/modules/CodeCoverageAutopas.cmake
  cmake/modules/autopas_eigen.cmake
  cmake/modules/autopas_gtest.cmake
  examples/md-flexible/MDFlexParser.cpp
  examples/md-flexible/MDFlexParser.h
  examples/md-flexible/main.cpp
  libs/CMakeLists.txt
  libs/eigen-eigen-323c052e1731.zip
  src/autopas/AutoPas.h
  src/autopas/CMakeLists.txt
  src/autopas/containers/CompatibleTraversals.h
  src/autopas/options/AcquisitionFunctionOption.h
  src/autopas/options/TuningStrategyOption.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/FeatureVector.h
  src/autopas/selectors/tuningStrategy/BayesianSearch.h
  src/autopas/selectors/tuningStrategy/FullSearch.h
  src/autopas/selectors/tuningStrategy/GaussianProcess.h
  src/autopas/selectors/tuningStrategy/TuningStrategyInterface.h
  src/autopas/utils/NumberSet.h
  src/autopas/utils/Random.h
  src/autopas/utils/StringUtils.h
  tests/testAutopas/tests/selectors/tuningStrategy/BayesianSearchTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/BayesianSearchTest.h
  tests/testAutopas/tests/selectors/tuningStrategy/GaussianProcessTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/GaussianProcessTest.h
  tests/testAutopas/tests/utils/NumberSetTest.cpp
  tests/testAutopas/tests/utils/StringUtilsTest.cpp
Labels: auto-tuning

#306 Fix GridGenerator::fillWithParticles
  examples/md-flexible/main.cpp
  tests/testAutopas/testingHelpers/GridGenerator.h
  tests/testAutopas/tests/containers/CellBlock3DTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/SlicedTraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
Labels: bug

#248 Linked-Cells: C04SoA traversal with combined SoA buffers
  src/autopas/containers/CompatibleTraversals.h
  src/autopas/containers/cellPairTraversals/C04BasedTraversal.h
  src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h
  src/autopas/containers/linkedCells/traversals/C04SoATraversal.h
  src/autopas/options/TraversalOption.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/utils/SoA.h
  src/autopas/utils/StringUtils.h
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/C04SoATraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/C04SoATraversalTest.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/selectors/AutoTunerTest.cpp
  tests/testAutopas/tests/utils/SoATest.cpp
  tests/testAutopas/tests/utils/StringUtilsTest.cpp
Labels: enhancement

#308 make updateContainer also return whether the container was updated
  examples/sph-mpi/sph-main-mpi.cpp
  examples/sph/sph-main.cpp
  src/autopas/AutoPas.h
  src/autopas/LogicHandler.h
  tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
Labels: ls1-integration

#307 Add generic to_string function, Bug fix NumberSet
  examples/sph/sph-main.cpp
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C04Traversal.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/utils/ArrayMath.h
  src/autopas/utils/ArrayUtils.h
  src/autopas/utils/NumberSet.h
  tests/testAutopas/tests/containers/CellBlock3DTest.cpp
  tests/testAutopas/tests/iterators/RegionParticleIteratorTest.cpp
  tests/testAutopas/tests/utils/ArrayMathTest.cpp
  tests/testAutopas/tests/utils/ArrayUtilsTest.cpp
  tests/testAutopas/tests/utils/NumberSetTest.cpp
Labels: bug, enhancement

#303 Refactor Newton3OnOffTest
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.h
Labels: refactoring, tests

#317 C04SoA: Bug fix
  src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h
Labels: bug

#315 makes RegionParticleIterators use increased search Regions when using LinkedCells
  src/autopas/containers/CellBlock3D.h
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
  tests/testAutopas/tests/autopasInterface/IteratorTest.cpp
  tests/testAutopas/tests/autopasInterface/IteratorTest.h
Labels: bug, ls1-integration

#320 Fix #318
  src/autopas/utils/SoAView.h
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
Labels: bug
