Repository AutoPas/AutoPas, pull requests merged in 2019-06, with the labels that each got.

#234 Bug fixes Newton3OnOffTest
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
Labels: bug, tests

#235 Refactoring: Move initTraversal/endTraversal to superclass CBasedTraversal
  src/autopas/containers/cellPairTraversals/C01BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C08BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C18BasedTraversal.h
  src/autopas/containers/cellPairTraversals/CBasedTraversal.h
Labels: refactoring

#218 Cell size factor for cell based verlet lists
  src/autopas/AutoPas.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/ContainerSelector.h
  tests/testAutopas/tests/containers/verletLists/VerletListsTest.cpp
  tests/testAutopas/tests/containers/verletLists/VerletListsTest.h
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTest.cpp
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.cpp
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.h
Labels: enhancement

#223 Adapt sph example to #215
  examples/CMakeLists.txt
  examples/sph-mpi/sph-main-mpi.cpp
  examples/sph-verlet/CMakeLists.txt
  examples/sph-verlet/README
  examples/sph-verlet/sph-main-verlet.cpp
  examples/sph/sph-main.cpp
  src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCellsHelpers.h
  src/autopas/pairwiseFunctors/FlopCounterFunctor.h
  src/autopas/pairwiseFunctors/Functor.h
  src/autopas/pairwiseFunctors/LJFunctorAVX.h
  src/autopas/sph/SPHCalcDensityFunctor.h
  src/autopas/sph/SPHCalcHydroForceFunctor.h
  src/autopas/utils/Logger.h
  tests/testAutopas/testingHelpers/NumThreadGuard.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.h
Labels: examples

#236 Tuning strategies
  examples/md-flexible/MDFlexParser.cpp
  examples/md-flexible/MDFlexParser.h
  examples/md-flexible/main.cpp
  src/autopas/AutoPas.h
  src/autopas/cells/FullParticleCell.h
  src/autopas/cells/RMMParticleCell2T.h
  src/autopas/containers/CompatibleTraversals.h
  src/autopas/containers/ParticleContainer.h
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/options/ContainerOption.h
  src/autopas/options/DataLayoutOption.h
  src/autopas/options/Newton3Option.h
  src/autopas/options/SelectorStrategyOption.h
  src/autopas/options/TraversalOption.h
  src/autopas/options/TuningStrategyOption.h
  src/autopas/particles/Particle.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/Configuration.h
  src/autopas/selectors/OptimumSelector.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/selectors/tuningStrategy/FullSearch.h
  src/autopas/selectors/tuningStrategy/TuningStrategyInterface.h
  src/autopas/utils/StringUtils.h
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/selectors/AutoTunerTest.cpp
  tests/testAutopas/tests/selectors/AutoTunerTest.h
  tests/testAutopas/tests/selectors/ContainerSelectorTest.cpp
  tests/testAutopas/tests/selectors/OptimumSelectorTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/FullSearchTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/FullSearchTest.h
  tests/testAutopas/tests/utils/StringUtilsTest.cpp
  tests/testAutopas/tests/utils/StringUtilsTest.h
Labels: auto-tuning, refactoring

#241 Coloring.cmake with generator expressions.
  CMakeLists.txt
  cmake/modules/CodeCoverage.cmake
  cmake/modules/coloring.cmake
Labels: cmake

#225 Format CMakeLists.txt using cmake-format
  CMakeLists.txt
  Jenkinsfile
  cmake/cmake-format.py
  cmake/modules/CodeCoverage.cmake
  cmake/modules/CodeCoverageAutopas.cmake
  cmake/modules/OpenMP.cmake
  cmake/modules/autopas_gtest.cmake
  cmake/modules/clang-format.cmake
  cmake/modules/clang-sanitizers.cmake
  cmake/modules/clang-tidy.cmake
  cmake/modules/cmake-format.cmake
  cmake/modules/coloring.cmake
  cmake/modules/cuda.cmake
  cmake/modules/doxygen.cmake
  cmake/modules/logging.cmake
  cmake/modules/other-compileroptions.cmake
  cmake/modules/vectorization.cmake
  examples/CMakeLists.txt
  examples/basic-cuda/CMakeLists.txt
  examples/basic/CMakeLists.txt
  examples/benchmark-cuda/CMakeLists.txt
  examples/cluster-test/CMakeLists.txt
  examples/md-flexible/CMakeLists.txt
  examples/sph-mpi/CMakeLists.txt
  examples/sph-traversals/CMakeLists.txt
  examples/sph-verlet/CMakeLists.txt
  examples/sph/CMakeLists.txt
  examples/sphDiagramGeneration/CMakeLists.txt
  src/CMakeLists.txt
  src/autopas/CMakeLists.txt
  tests/CMakeLists.txt
  tests/testAutopas/CMakeLists.txt
  version.cmake
Labels: cmake, low priority

#244 MemProfiler Cpp style
  src/autopas/utils/MemoryProfiler.cpp
Labels: bug

#239 Container selector info
  .gitignore
  examples/md-flexible/MDFlexParser.cpp
  examples/md-flexible/MDFlexParser.h
  examples/md-flexible/main.cpp
  src/autopas/AutoPas.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/Configuration.h
  src/autopas/selectors/ContainerSelector.h
  src/autopas/selectors/ContainerSelectorInfo.h
  src/autopas/selectors/TraversalSelectorInfo.h
  src/autopas/selectors/tuningStrategy/FullSearch.h
  src/autopas/utils/NumberSet.h
  src/autopas/utils/StringUtils.h
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/selectors/AutoTunerTest.cpp
  tests/testAutopas/tests/selectors/ContainerSelectorTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/FullSearchTest.cpp
  tests/testAutopas/tests/utils/NumberSetTest.cpp
  tests/testAutopas/tests/utils/StringUtilsTest.cpp
Labels: auto-tuning, refactoring

#233 Linked-Cells: Combine SoA Buffer C01
  src/autopas/containers/CompatibleTraversals.h
  src/autopas/containers/cellPairTraversals/C01BasedTraversal.h
  src/autopas/containers/cellPairTraversals/CBasedTraversal.h
  src/autopas/containers/cellPairTraversals/CellPairTraversal.h
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/options/TraversalOption.h
  src/autopas/pairwiseFunctors/CellFunctor.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/utils/AlignedAllocator.h
  src/autopas/utils/NumberSet.h
  src/autopas/utils/SoA.h
  src/autopas/utils/SoAStorage.h
  src/autopas/utils/StringUtils.h
  tests/testAutopas/testingHelpers/NumThreadGuard.h
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/containers/directSum/DirectSumTraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/C01TraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/selectors/AutoTunerTest.cpp
  tests/testAutopas/tests/utils/SoATest.cpp
  tests/testAutopas/tests/utils/StringUtilsTest.cpp
Labels: enhancement

#243 remove raw ptr from sph-diagram-generation
  examples/sphDiagramGeneration/sph-diagram-generation.cpp
Labels: refactoring

#237 Add contribution guidelines
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
  .remarkrc.yaml
  README.md
Labels: documentation, help wanted, low priority

#249 Refactoring
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/linkedCells/traversals/LinkedCellTraversalInterface.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletLists/traversals/TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletLists/traversals/VerletTraversalInterface.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
Labels: refactoring

#252 Correct wrong formatted CMake comments
  cmake/modules/CodeCoverage.cmake
Labels: cmake

#253 Traversal interface rework
  examples/sphDiagramGeneration/sph-diagram-generation.cpp
  src/autopas/containers/cellPairTraversals/C01BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C08BasedTraversal.h
  src/autopas/containers/cellPairTraversals/C18BasedTraversal.h
  src/autopas/containers/cellPairTraversals/CBasedTraversal.h
  src/autopas/containers/cellPairTraversals/CellPairTraversal.h
  src/autopas/containers/cellPairTraversals/DummyTraversal.h
  src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
  src/autopas/containers/cellPairTraversals/TraversalInterface.h
  src/autopas/containers/directSum/DirectSumTraversal.h
  src/autopas/containers/linkedCells/traversals/C01CudaTraversal.h
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C08Traversal.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/containers/linkedCells/traversals/SlicedTraversal.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletLists/traversals/TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletLists/traversals/VerletTraversalInterface.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C01TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C18TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/SlicedTraversalVerlet.h
  src/autopas/options/Newton3Option.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/TraversalSelector.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/pairwiseFunctors/FlopCounterTest.cpp
  tests/testAutopas/tests/selectors/AutoTunerTest.cpp
Labels: refactoring

#259 Removed newton3 parameter from all iteratePairwise methods in the containers
  examples/cluster-test/cluster-test.cpp
  examples/sph-mpi/sph-main-mpi.cpp
  examples/sph-traversals/sph-traversals.cpp
  examples/sph-verlet/sph-main-verlet.cpp
  examples/sph/sph-main.cpp
  examples/sphDiagramGeneration/sph-diagram-generation.cpp
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/selectors/AutoTuner.h
  tests/testAutopas/tests/autopasInterface/Newton3OnOffTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletClusterListsTest.cpp
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsTest.cpp
  tests/testAutopas/tests/containers/verletClusterLists/VerletClusterListsTest.cpp
  tests/testAutopas/tests/containers/verletLists/VerletListsTest.cpp
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTest.cpp
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.cpp
  tests/testAutopas/tests/sph/SPHTest.cpp
Labels: refactoring

#261 ContainerSelectorTest: Refactoring and bug fixing
  tests/testAutopas/tests/selectors/ContainerSelectorTest.cpp
Labels: bug, refactoring, tests

#266 ArrayMath: Refactoring, new function static_cast_array
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/utils/ArrayMath.h
  tests/testAutopas/tests/utils/ArrayMathTest.cpp
Labels: refactoring

#267 ThreeDimensionalMapping: Refactoring
  src/autopas/utils/ThreeDimensionalMapping.h
Labels: refactoring

#246 Bump CMake version
  .lgtm.yml
  CMakeLists.txt
  README.md
  cmake/modules/OpenMP.cmake
  cmake/modules/format.cmake
  cmake/modules/other-compileroptions.cmake
  cmake/modules/vectorization.cmake
Labels: cmake

#215 [WIP] AutoPas interface refactoring
  cmake/modules/CodeCoverage.cmake
  cmake/modules/autopas_gtest.cmake
  cmake/modules/clang-format.cmake
  cmake/modules/cmake-format.cmake
  examples/CMakeLists.txt
  examples/sph-mpi/sph-main-mpi.cpp
  examples/sph-verlet/CMakeLists.txt
  examples/sph-verlet/README
  examples/sph-verlet/sph-main-verlet.cpp
  examples/sph/sph-main.cpp
  src/autopas/AutoPas.h
  src/autopas/autopasIncludes.h
  src/autopas/cells/RMMParticleCell2T.h
  src/autopas/containers/CellBlock3D.h
  src/autopas/containers/CellBorderAndFlagManager.h
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletListHelpers.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCellsHelpers.h
  src/autopas/iterators/ParticleIterator.h
  src/autopas/iterators/RegionParticleIterator.h
  src/autopas/pairwiseFunctors/FlopCounterFunctor.h
  src/autopas/pairwiseFunctors/Functor.h
  src/autopas/particles/Particle.h
  src/autopas/sph/SPHCalcDensityFunctor.h
  src/autopas/sph/SPHCalcHydroForceFunctor.h
  src/autopas/utils/AutoPasMacros.h
  src/autopas/utils/Logger.h
  tests/testAutopas/mocks/MockVerletLists.h
  tests/testAutopas/testingHelpers/NumThreadGuard.h
  tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
  tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.h
  tests/testAutopas/tests/containers/directSum/DirectSumContainerTest.cpp
  tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.h
  tests/testAutopas/tests/containers/verletLists/VerletListsTest.cpp
  tests/testAutopas/tests/selectors/ContainerSelectorTest.cpp
Labels: ls1-integration

#279 Remove rebuild function from CellPairTraversal
  src/autopas/containers/cellPairTraversals/CellPairTraversal.h
  src/autopas/containers/cellPairTraversals/SlicedBasedTraversal.h
Labels: refactoring

#287 fix thread guards
  tests/testAutopas/tests/containers/linkedCells/traversals/SlicedTraversalTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalRaceConditionTest.cpp
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/containers/verletListsCells/VerletListsCellsTraversalTest.cpp
Labels: bug

#286 remove ParticleCell template from TraversalSelectorInfo
  examples/sphDiagramGeneration/sph-diagram-generation.cpp
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/selectors/TraversalSelector.h
  src/autopas/selectors/TraversalSelectorInfo.h
  tests/testAutopas/tests/containers/linkedCells/traversals/TraversalTest.cpp
  tests/testAutopas/tests/selectors/TraversalSelectorTest.cpp
Labels: refactoring

#238 Linked-Cells: sort cells
  src/autopas/cells/FullParticleCell.h
  src/autopas/cells/ParticleCell.h
  src/autopas/cells/RMMParticleCell2T.h
  src/autopas/cells/SortedCellView.h
  src/autopas/containers/CellBlock3D.h
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C08CellHandler.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/pairwiseFunctors/CellFunctor.h
  src/autopas/utils/ArrayMath.h
  tests/testAutopas/tests/cells/SortedCellViewTest.cpp
  tests/testAutopas/tests/cells/SortedCellViewTest.h
  tests/testAutopas/tests/utils/ArrayMathTest.cpp
Labels: enhancement
