Repository AutoPas/AutoPas, pull requests merged in 2019-08, with the labels that each got.

#326 optimize getNearbyHaloCells function in CellBlock3D
  src/autopas/containers/CellBlock3D.h
Labels: ls1-integration, optimization

#328 AVX Functor shortcut
  src/autopas/pairwiseFunctors/LJFunctorAVX.h
Labels: optimization

#334 Remove NULL and assert
  .github/CONTRIBUTING.md
  Jenkinsfile
  src/autopas/cells/FullParticleCell.h
  src/autopas/cells/RMMParticleCell2T.h
  src/autopas/containers/verletListsCellBased/verletLists/neighborLists/asBuild/AsBuildPairGeneratorFunctor.h
  src/autopas/pairwiseFunctors/Functor.h
  src/autopas/utils/SoA.h
  src/autopas/utils/WrapOpenMP.h
  tests/testAutopas/testingHelpers/NumThreadGuard.h
Labels: Jenkins

#340 More Data in VTK Files
  examples/md-flexible/Simulation.h
Labels: examples

#339 Refactoring
  docs/C08TraversalScheme.py
  examples/md-flexible/plotScript.gp
  src/autopas/AutoPas.h
  src/autopas/LogicHandler.h
  src/autopas/cells/FullParticleCell.h
  src/autopas/containers/CellBlock3D.h
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/verletLists/VarVerletLists.h
  src/autopas/containers/verletListsCellBased/verletLists/VerletLists.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/iterators/ParticleIterator.h
  src/autopas/iterators/RegionParticleIterator.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/ContainerSelector.h
  src/autopas/selectors/OptimumSelector.h
  src/autopas/selectors/tuningStrategy/BayesianSearch.h
  src/autopas/selectors/tuningStrategy/FullSearch.h
  src/autopas/selectors/tuningStrategy/TuningStrategyInterface.h
  src/autopas/sph/SPHCalcHydroForceFunctor.h
  src/autopas/sph/SPHKernels.h
  src/autopas/utils/ArrayMath.h
  tests/testAutopas/tests/utils/ArrayMathTest.cpp
Labels: enhancement, refactoring

#338 Remove "Particle" template parameter
  .github/CONTRIBUTING.md
  examples/benchmark-cuda/main.cpp
  examples/sph-traversals/sph-traversals.cpp
  examples/sphDiagramGeneration/sph-diagram-generation.cpp
  src/autopas/containers/ParticleContainer.h
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/neighborLists/VerletNeighborListInterface.h
  src/autopas/containers/verletListsCellBased/verletLists/neighborLists/asBuild/VerletNeighborListAsBuild.h
  src/autopas/containers/verletListsCellBased/verletLists/traversals/TraversalVerlet.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/ContainerSelector.h
  tests/testAutopas/tests/containers/CudaTraversalVersusDirectSumTest.cpp
  tests/testAutopas/tests/containers/CudaTraversalVersusDirectSumTest.h
  tests/testAutopas/tests/containers/LinkedCellsVersusDirectSumTest.h
  tests/testAutopas/tests/containers/LinkedCellsVersusVarVerletListsTest.h
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletClusterListsTest.h
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsCellsTest.h
  tests/testAutopas/tests/containers/LinkedCellsVersusVerletListsTest.h
  tests/testAutopas/tests/containers/directSum/DirectSumContainerTest.cpp
  tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.cpp
  tests/testAutopas/tests/containers/linkedCells/LinkedCellsTest.h
  tests/testAutopas/tests/iterators/ParticleIteratorTest.cpp
  tests/testAutopas/tests/iterators/RegionParticleIteratorTest.cpp
  tests/testAutopas/tests/iterators/RegionParticleIteratorTest.h
  tests/testAutopas/tests/sph/SPHTest.cpp
Labels: refactoring
