Repository AutoPas/AutoPas, pull requests merged in 2020-05, with the labels that each got.

#455 Updates the documentation of the ownership.
  README.md
Labels: documentation

#454 SuperClass for tuning strategies and user input for PredicitveTuning
  examples/md-flexible/Simulation.h
  examples/md-flexible/parsing/CLIParser.cpp
  examples/md-flexible/parsing/CLIParser.h
  examples/md-flexible/parsing/MDFlexConfig.cpp
  examples/md-flexible/parsing/MDFlexConfig.h
  examples/md-flexible/parsing/MDFlexParser.cpp
  examples/md-flexible/parsing/MDFlexParser.h
  examples/md-flexible/parsing/YamlParser.cpp
  examples/md-flexible/parsing/YamlParser.h
  src/autopas/AutoPas.h
  src/autopas/options/TuningStrategyOption.h
  src/autopas/selectors/AutoTuner.h
  src/autopas/selectors/tuningStrategy/ActiveHarmony.h
  src/autopas/selectors/tuningStrategy/BayesianSearch.h
  src/autopas/selectors/tuningStrategy/FullSearch.h
  src/autopas/selectors/tuningStrategy/GaussianProcess.cpp
  src/autopas/selectors/tuningStrategy/GaussianProcess.h
  src/autopas/selectors/tuningStrategy/PredictiveTuning.h
  src/autopas/selectors/tuningStrategy/RandomSearch.h
  src/autopas/selectors/tuningStrategy/SetSearchSpaceBasedTuningStrategy.h
  src/autopas/selectors/tuningStrategy/TuningStrategyFactory.cpp
  src/autopas/selectors/tuningStrategy/TuningStrategyFactory.h
  src/autopas/selectors/tuningStrategy/TuningStrategyInterface.h
  tests/testAutopas/tests/options/OptionTest.cpp
  tests/testAutopas/tests/options/OptionTest.h
  tests/testAutopas/tests/selectors/tuningStrategy/PredictiveTuningTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/PredictiveTuningTest.h
Labels: auto-tuning

#461 when a number of tuning-phases is specified finish the simulation whe…
  examples/md-flexible/README.md
  examples/md-flexible/Simulation.h
  examples/md-flexible/parsing/CLIParser.cpp
  examples/md-flexible/parsing/MDFlexConfig.h
  examples/md-flexible/parsing/YamlParser.cpp
Labels: examples

#447 C04hcp traversal
  src/autopas/containers/CompatibleTraversals.h
  src/autopas/containers/linkedCells/traversals/C04HCP.h
  src/autopas/containers/linkedCells/traversals/C04Traversal.h
  src/autopas/options/TraversalOption.h
  src/autopas/selectors/TraversalSelector.h
  tests/testAutopas/tests/options/OptionTest.cpp
  tests/testAutopas/tests/selectors/AutoTunerTest.cpp
Labels: enhancement

#451 Bunch of minor fixes
  .gitignore
  examples/md-flexible/Simulation.h
  examples/md-flexible/main.cpp
  examples/md-flexible/parsing/CLIParser.cpp
  examples/md-flexible/scripts/measurePerf.sh
  examples/md-flexible/scripts/plotScript.gp
  examples/md-flexible/tests/ParticlePropertiesLibraryTest.cpp
  src/autopas/AutoPas.h
  src/autopas/LogicHandler.h
  src/autopas/containers/CellBlock3D.h
  src/autopas/containers/CellBorderAndFlagManager.h
  src/autopas/containers/CompatibleTraversals.h
  src/autopas/containers/ParticleContainer.h
  src/autopas/containers/ParticleContainerInterface.h
  src/autopas/containers/TraversalInterface.h
  src/autopas/containers/directSum/DirectSum.h
  src/autopas/containers/directSum/DirectSumTraversal.h
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/linkedCells/traversals/C01CudaTraversal.h
  src/autopas/containers/linkedCells/traversals/C01Traversal.h
  src/autopas/containers/linkedCells/traversals/C04HCP.h
  src/autopas/containers/linkedCells/traversals/C04SoATraversal.h
  src/autopas/containers/linkedCells/traversals/C04Traversal.h
  src/autopas/containers/linkedCells/traversals/C08Traversal.h
  src/autopas/containers/linkedCells/traversals/C18Traversal.h
  src/autopas/containers/linkedCells/traversals/SlicedTraversal.h
  src/autopas/containers/verletClusterCells/traversals/VerletClusterCellsTraversal.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
  src/autopas/containers/verletClusterLists/traversals/VerletClustersColoringTraversal.h
  src/autopas/containers/verletClusterLists/traversals/VerletClustersStaticTraversal.h
  src/autopas/containers/verletClusterLists/traversals/VerletClustersTraversal.h
  src/autopas/containers/verletListsCellBased/VerletListsLinkedBase.h
  src/autopas/containers/verletListsCellBased/verletLists/traversals/TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletLists/traversals/VarVerletTraversalAsBuild.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C01TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/C18TraversalVerlet.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/SlicedTraversalVerlet.h
  src/autopas/selectors/Configuration.h
  src/autopas/selectors/OptimumSelector.h
  src/autopas/utils/AutoPasMacros.h
Labels: refactoring

#467 removed outdated comment
  src/autopas/AutoPas.h
  src/autopas/containers/CompatibleTraversals.h
  tests/testAutopas/testingHelpers/EmptyFunctor.h
Labels: documentation

#449 Bayesian Search for mixed discrete-continuous variables
  examples/md-flexible/parsing/MDFlexConfig.h
  src/autopas/AutoPas.h
  src/autopas/options/AcquisitionFunctionOption.h
  src/autopas/options/TuningStrategyOption.h
  src/autopas/selectors/FeatureVector.h
  src/autopas/selectors/tuningStrategy/ActiveHarmony.h
  src/autopas/selectors/tuningStrategy/BayesianClusterSearch.h
  src/autopas/selectors/tuningStrategy/BayesianSearch.h
  src/autopas/selectors/tuningStrategy/GaussianModel/AcquisitionFunction.h
  src/autopas/selectors/tuningStrategy/GaussianModel/GaussianCluster.h
  src/autopas/selectors/tuningStrategy/GaussianModel/GaussianHyperparameters.cpp
  src/autopas/selectors/tuningStrategy/GaussianModel/GaussianHyperparameters.h
  src/autopas/selectors/tuningStrategy/GaussianModel/GaussianProcess.h
  src/autopas/selectors/tuningStrategy/GaussianProcess.h
  src/autopas/selectors/tuningStrategy/RandomSearch.h
  src/autopas/selectors/tuningStrategy/TuningStrategyFactory.cpp
  src/autopas/utils/Math.cpp
  src/autopas/utils/Math.h
  src/autopas/utils/NumberSetFinite.h
  src/autopas/utils/Random.h
  tests/testAutopas/tests/options/OptionTest.cpp
  tests/testAutopas/tests/selectors/FeatureVectorTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/ActiveHarmonyTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/BayesianClusterSearchTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/BayesianClusterSearchTest.h
  tests/testAutopas/tests/selectors/tuningStrategy/BayesianSearchTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/FullSearchTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianClusterTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianClusterTest.h
  tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianProcessTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/GaussianModel/GaussianProcessTest.h
  tests/testAutopas/tests/selectors/tuningStrategy/RandomSearchTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/TuningStrategyTest.cpp
  tests/testAutopas/tests/selectors/tuningStrategy/TuningStrategyTest.h
Labels: auto-tuning

#469 fancy help messages, doc and completions
  .github/CONTRIBUTING.md
  CMakeLists.txt
  Jenkinsfile
  cmake/modules/doxygen.cmake
  examples/md-flexible/CMakeLists.txt
  examples/md-flexible/Doxyfile.in
  examples/md-flexible/README.md
  examples/md-flexible/completion/README.md
  examples/md-flexible/completion/zsh/_md-flexible
  examples/md-flexible/parsing/CLIParser.cpp
  examples/md-flexible/parsing/CLIParser.h
  examples/md-flexible/parsing/MDFlexConfig.cpp
  examples/md-flexible/parsing/MDFlexConfig.h
  examples/md-flexible/parsing/MDFlexParser.h
  examples/md-flexible/parsing/YamlParser.cpp
  examples/md-flexible/src/BoundaryConditions.h
  examples/md-flexible/src/Checkpoint.h
  examples/md-flexible/src/Generator.h
  examples/md-flexible/src/Objects/CubeGauss.h
  examples/md-flexible/src/Objects/CubeGrid.h
  examples/md-flexible/src/Objects/CubeUniform.h
  examples/md-flexible/src/Objects/Objects.h
  examples/md-flexible/src/Objects/Sphere.h
  examples/md-flexible/src/PrintableMolecule.h
  examples/md-flexible/src/Simulation.h
  examples/md-flexible/src/Thermostat.h
  examples/md-flexible/src/TimeDiscretization.h
  examples/md-flexible/src/main.cpp
  examples/md-flexible/src/parsing/CLIParser.cpp
  examples/md-flexible/src/parsing/CLIParser.h
  examples/md-flexible/src/parsing/MDFlexConfig.cpp
  examples/md-flexible/src/parsing/MDFlexConfig.h
  examples/md-flexible/src/parsing/MDFlexParser.cpp
  examples/md-flexible/src/parsing/MDFlexParser.h
  examples/md-flexible/src/parsing/ParserExitCodes.h
  examples/md-flexible/src/parsing/YamlParser.cpp
  examples/md-flexible/src/parsing/YamlParser.h
  examples/md-flexible/tests/CMakeLists.txt
  examples/md-flexible/tests/GeneratorsTest.cpp
  examples/md-flexible/tests/ObjectsTest.h
  examples/md-flexible/tests/ParticlePropertiesLibraryTest.cpp
  examples/md-flexible/tests/ThermostatTest.cpp
  examples/md-flexible/tests/TimeDiscretizationTest.cpp
  examples/md-flexible/tests/YamlParserTest.cpp
  src/autopas/namespaces.h
  src/autopas/utils/SoAStorage.h
  src/autopas/utils/TupleUtils.h
Labels: documentation, enhancement, examples, refactoring

#477 Fix parallel Access to Random Engine in Thermostat
  examples/md-flexible/src/Thermostat.h
Labels: bug
