Repository AutoPas/AutoPas, pull requests merged in 2024-06, with the labels that each got.

#882 Fix bug that broke exploding liquid
  src/autopas/containers/linkedCells/LinkedCells.h
  src/autopas/containers/linkedCells/LinkedCellsReferences.h
  src/autopas/containers/octree/Octree.h
  src/autopas/containers/verletClusterLists/VerletClusterLists.h
Labels: bug, high priority

#883 Refactor RuleBasedTuning class to avoid unused variable warnings.
  src/autopas/tuning/tuningStrategy/ruleBasedTuning/RuleBasedTuning.cpp
  src/autopas/tuning/tuningStrategy/ruleBasedTuning/RuleBasedTuning.h
Labels: bug, low priority

#893 Make getNearbyHaloCells reserve
  src/autopas/containers/CellBlock3D.h
Labels: bug

#872 VLC C08
  src/autopas/containers/LoadEstimators.h
  src/autopas/containers/cellPairTraversals/C18BasedTraversal.h
  src/autopas/containers/linkedCells/traversals/LCC18Traversal.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCellsHelpers.cpp
  src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCellsHelpers.h
  src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCAllCellsGeneratorFunctor.h
  src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCAllCellsNeighborList.h
  src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCCellPairGeneratorFunctor.h
  src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCCellPairNeighborList.h
  src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCNeighborListInterface.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCC08Traversal.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCCellPairC08Traversal.h
  src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCCellPairTraversalInterface.h
  src/autopas/namespaces.h
  src/autopas/options/TraversalOption.h
  src/autopas/tuning/selectors/ContainerSelector.h
  src/autopas/tuning/selectors/TraversalSelector.h
  src/autopas/utils/ThreeDimensionalMapping.h
  tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp
  tests/testAutopas/tests/containers/verletListsCellBased/verletListsCells/PairwiseVerletListsTest.cpp
  tests/testAutopas/tests/containers/verletListsCellBased/verletListsCells/PairwiseVerletListsTest.h
  tests/testAutopas/tests/containers/verletListsCellBased/verletListsCells/VerletListsCellsTest.cpp
  tests/testAutopas/tests/tuning/AutoTunerTest.cpp
Labels: enhancement
